-- AlterTable
ALTER TABLE `Service`
  ADD COLUMN `category` VARCHAR(30) NULL,
  ADD COLUMN `goals` JSON NULL,
  ADD COLUMN `ratingAvg` DOUBLE NOT NULL DEFAULT 5,
  ADD COLUMN `bookedCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `tag` VARCHAR(80) NULL,
  ADD COLUMN `imageUrl` VARCHAR(500) NULL,
  ADD COLUMN `heroImageUrl` VARCHAR(500) NULL;
